src/Dockerfile
src/requirements.txt

Add Oracle drivers to connect to GOB data sources.
Most of the data sources are in Oracle databases.
For example Meetbouten.

ORACLE Drivers

---

src/example/meetbouten_database.json
src/gobimportclient/__main__.py
src/gobimportclient/connector/config.py
src/gobimportclient/connector/database.py
src/gobimportclient/converter.py
src/gobimportclient/import_client.py
src/gobimportclient/reader/database.py
src/requirements.txt

Grondslag is the durable source for Meetbouten.
The import is by means of a query (join of 4 tables)
Next step is to remove the types from the mapping
rename gob_model to gob_mapping
and to remove gob_model from the message header

Import Meetbouten from Grondslag

---

src/gobimportclient/import_client.py
src/gobimportclient/validator/__init__.py
src/tests/fixtures.py
src/tests/test_validator.py

Extra validation rules were added to add warning level quality control. Messages are being logged with reports on how many invalid records per attribute.
Validator has been made into a class because a reference to the process aware logging was needed which is defined in import client. In a refactor I think we should move the process aware logger to the core.

Added quality control to import client

---

src/gobimportclient/connector/config.py

The port for the grondslag database needs to be different on the acceptance environment. This fix allows an environment variable to set it.

Add grondslag port override env var

---

src/data/stadsdelen.conversion.json
src/data/stadsdelen.json
src/gobimport/connector/config.py
src/gobimport/connector/database.py
src/gobimport/import_client.py
src/gobimport/injections.py
src/test.sh
src/tests/test_connector.py
src/tests/test_injections.py

Import DGDialog (replaces DIVA)
Inject conversion data from DIVA into DGDialog import
Allow usage of Oracle Service Names, besides SID's

Dgdialog import, conversion injections, Oracle service name

---

src/data/bouwblokken.diva.json
src/data/buurten.diva.json
src/data/meetbouten.json
src/data/metingen.json
src/data/peilmerken.json
src/data/referentiepunten.json
src/data/rollagen.json
src/data/stadsdelen.diva.json
src/data/stadsdelen.json
src/data/test/test.json
src/data/wijken.diva.json
src/gobimport/converter.py
src/gobimport/import_client.py
src/requirements.txt

The id of an entity is knowledge of GOB Model, not of an import mapping
Fixed bug in source id; entity id (+ datum begin geldigheid for entities with state)

Remove entity id from mapping

---

src/data/stadsdelen.json

Previous DIVA contents should be loaded before
DGDialog can be imported

DGDialog depends on DIVA

---

src/data/bouwblokken.conversion.json
src/data/bouwblokken.json
src/data/buurten.conversion.json
src/data/buurten.json
src/data/stadsdelen.json
src/gobimport/import_client.py
src/test.sh
src/tests/test_converter.py

Import with conversion data from DIVA
Identification of DIVA are copied when exists
Volgnummer of DIVA is followed when exists
If no previous DIVA entry exists, None is set for identification and the volgnummer remains unchanged
In a next ticket DGDialog entries without id should be given (or inserted when already exist) an id automatically.
This requires:
- Identifying the collection as missing id (probably use inject.conversions ?)
- An extra step before compare to insert ids

Import buurten and bouwblokken from DGDialog

---

src/gobimport/enricher/meetbouten.py

Also catch attribute errors when trying to split refereert_aan in metingen

Catch AttributeError in metingen enrich

---

src/gobimport/entity_validator/__init__.py

The validation for states was always returning true when no specific entity validator was specified.

Fix entity validation for states

---

src/data/bouwblokken.json
src/data/buurten.json
src/data/ggpgebieden.json
src/data/ggwgebieden.json
src/data/stadsdelen.json
src/data/wijken.json
src/gobimport/enricher/gebieden.py
src/gobimport/entity_validator/__init__.py
src/gobimport/entity_validator/gebieden.py
src/gobimport/import_client.py
src/gobimport/injections.py
src/gobimport/validator/__init__.py
src/tests/enricher/test_enrich_gebieden.py
src/tests/entity_validator/test_enrich_gebieden.py
src/tests/entity_validator/test_entity_validator.py

Add a +-1 operator to let volgnummers start at 1 for new entities
Set volgnummer and registratiedatum for GGW/GGP imports
Enable bouwblokken/buurten validations
Derive identification from import specification

Improve imports

---

src/data/verblijfsobjecten.json

Only import actual objects
This allows for an import of verblijfsobjecten in the acceptance environment

Limit verblijfsobjecten

---

src/data/bouwblokken.conversion.json
src/data/bouwblokken.json
src/data/buurten.conversion.json
src/data/buurten.json
src/data/stadsdelen.json
src/data/wijken.json

Source id was added to gebieden imports and conversion files were re-added to make sure bouwblokken en buurten are working again.

Add source_id to gebieden import

---

src/data/verblijfsobjecten.json

Bronwaarde was receiving both the identificatie and volgnummer for the ligt_in_panden relation. Removing the volgnummer will allow the relation to be made

Remove volgnummer from ligt_in_panden

---

src/data/brk.gemeentes.json

We’re currently deciding how we should handle the lack of states for gemeentes, as a temporary solution a literal start date was added

Use a literal value for gemeentes

---

src/gobimport/converter.py
src/requirements.txt
src/tests/test_converter.py

If a reference receives a dictionary, all values other than the specified bronwaarde will be moved into broninfo

Clean references for bronwaarde and broninfo

---

src/data/bouwblokken.json

Ranking on code resulted in a duplicate id error. Logic is now equal to buurten and wijken

Update dense rank on guid for bouwblokken

---

src/data/ggpgebieden.json
src/data/ggwgebieden.json
src/gobimport/enricher/gebieden.py
src/gobimport/import_client.py
src/gobimport/validator/__init__.py
src/requirements.txt
src/test.sh
src/tests/enricher/test_enrich_gebieden.py
src/tests/fixtures.py
src/tests/test_validator.py

Changing volgnummer on GGW/GGP resulted in some findings on entity validation and convertion. The code assumed an entity with states always has a column named ‘volgnummer’ while this should be configurable in the import mapping. Fox example the column in the GGW/GGP files was named ‘VOLGNUMMER’. Changes were made to core and validator to make this possible.

Use volgnummer from column on GGW GGP

---

src/data/metingen.json
src/data/verblijfsobjecten.json
src/gobimport/__main__.py
src/gobimport/config.py
src/gobimport/import_client.py
src/gobimport/reader.py
src/requirements.txt
src/tests/test_main.py
src/tests/test_reader.py

Add a demo import mode for metingen: some_day
Add an import mode for verblijfsobjecten: recent
Large imports should all get a "recent" import mode to only import recently added or changed entities.
Partial imports can be started using for example:
python -m gobworkflow.start import meetbouten metingen "" some_day
This PR depends on the corresponding PR for gobupload to handle partial uploads

Partial upload

---

src/data/dossiers.json

The group by query resulted in duplicate primary keys, added MAX to the creation date to get the latest record

Fix dossiers import query

---

src/requirements.txt

QA update stores the string value of any "betwijfelde waarde"
A "betwijfelde waarde" can be of any type.
When the type is a Decimal for instance the JSON serialisation would fail in the upload process
By converting the value to a string the string representation is stored and any serialisation errors are prevented

Update Core for QA "betwijfelde waarde"

---

src/requirements.txt

QA update stores the string value of any "betwijfelde waarde"
A "betwijfelde waarde" can be of any type.
When the type is a Decimal for instance the JSON serialisation would fail in the upload process
By converting the value to a string the string representation is stored and any serialisation errors are prevented

Release update Core for QA "betwijfelde waarde"

---

src/requirements.txt

Without the dry_run parameter GOB will generate the Amsterdamse Sleutel
Before, this was done by DIVA

Update Config, remove dry_run for Amsterdamse Sleutel

---

src/gobimport/converter.py
src/requirements.txt
src/test.sh
src/tests/test_converter.py

Log a data error when a type conversion fails.
Before this change the GOB-Import process would crash.
Now all type conversion errors are reported as data-errors.
This stops any further processing but the use can still see the data-errors.

PGB 1280 string in numeriek veld

---

src/gobimport/converter.py
src/gobimport/import_client.py
src/requirements.txt
src/tests/test_converter.py

If a conversion fails an issue is logged (data-error).
The id and any seqnr of the row is included in the Issue.
Data conversion errors occur when the input is still in the original format.
A GOB-Like row is built to use the standard Issue logic

Log issue on conversion error

---

src/gobimport/validator/__init__.py

Checks with a level of fatal will stop the import process, that should not happen for this data error

Changed QA level from fatal to warning for documentnummer

---

src/gobimport/validator/__init__.py
src/requirements.txt

This PR contains 2 changes:
- Updated gob-config version so correct queries are used for importing WKPB dossiers and brondocumenten
- Modified QA check for peilmerken from unused name field to identificatie

Wkpb import changes and qa check peilmerken fixed

---

src/gobimport/entity_validator/bag.py
src/gobimport/validator/__init__.py
src/tests/entity_validator/test_bag_validator.py

Validation added only for objects from amsterdam (starting with 0363) or from the source app Neuron

Add validation only for objects from Amsterdam

---

src/gobimport/validator/__init__.py

The value was a JSON object, so we need to check if the omschrijving is empty

Change qa check to check omschrijving

---

src/gobimport/__main__.py
src/gobimport/import_client.py
src/requirements.txt
src/tests/test_main.py

* Import as standalone application
- if args are given, start standalone
- no args, connect to messagebroker
* Use WorkflowCommands from gob-core
* refactor handle_import_msg for standalone
* Update core
- Use as standalone app
* Use Optional typing on argument
* Update core

Import as standalone application (#728)

---

src/gobimport/__main__.py
src/requirements.txt

- The logger is configured in gob-core version >= _v1.9.0_ in `_on_message` 
- Not necessary to configure this in the handler anymore. 
- Applies to worfklow and standalone mode

Remove logging configure

---

src/gobimport/entity_validator/__init__.py
src/gobimport/entity_validator/bag.py
src/gobimport/entity_validator/gebieden.py
src/gobimport/entity_validator/state.py
src/gobimport/import_client.py
src/gobimport/merger.py
src/gobimport/validator/__init__.py
src/requirements.txt
src/tests/entity_validator/test_init.py
src/tests/entity_validator/test_state_validator.py
src/tests/test_import_client.py
src/tests/test_merger.py

Problem: 
A 'merged' dataset imports from 2 different sources and merges certain fields for both entities. We validate the states of an entity in the EntityValidator, called during import. The issue doesn't appear in case of two different `entity_id`s, configured in gob-config. This because we cache these `entity_id` as key for the states. This is equal to validating 2 separate datasets, because the `entity_id` (probably) never match. In the bouwblokken case, the `entity_id` is the same, so the StateValidator errors on encountering the same volgnummer for an entity.
During importing a merged dataset we pass the `EntityValidator` two times:
- Merger.prepare, which adds all (to be merged) entities to the volgnummers and enddate cache. 
- the actual import, we validate the now merged entity …

Don't validate merged entities twice

---

src/gobimport/entity_validator/__init__.py
src/gobimport/entity_validator/bag.py
src/gobimport/entity_validator/gebieden.py
src/gobimport/entity_validator/state.py
src/gobimport/import_client.py
src/gobimport/merger.py
src/gobimport/validator/__init__.py
src/requirements.txt
src/tests/entity_validator/test_init.py
src/tests/entity_validator/test_state_validator.py
src/tests/test_import_client.py
src/tests/test_merger.py

* Drop merged entity from EntityValidator
* Update config v0.8.2
* Return early during validate instead of drop
* Add tests validate merged
* Silence test warning

Don't validate merged entities twice (#767)

---

src/.flake8
src/Dockerfile
src/gobimport/__init__.py
src/pyproject.toml
src/pytest.ini
src/requirements.txt
src/test.sh

- pyproject.toml is set up as a generic file we can use in any other repo
- requires flake8-pyproject package in gobcore
- Uncomment/enable checks per file in test.sh
included checks
- mypy
- pytest
- coverage
- black
- isort
- flake8
depends on https://github.com/Amsterdam/GOB-Core/pull/703

Add standard code checks to repo

---

src/gobimport/import_client.py
src/gobimport/reader.py
src/tests/test_import_client.py
src/tests/test_reader.py

Make sure we disconnect on exceptions

Explicitely call `disconnect` when exiting Reader context

---

src/requirements.txt

Release v0.19.0 will be created from PR https://github.com/Amsterdam/GOB-Config/pull/188

Update Config to v0.19.0 with BRK2 ADB imports
