Amsterdam/GOB-Import

README.md
src/example/meetbouten.json
src/example/metingen.json
src/gobimportclient/converter.py
src/gobimportclient/import_client.py
src/requirements.txt

Slightly modified README.md to reflect changes in other modules. And introduced references to the GOBi TypeSystem.

Added GOB Typesystem

---

src/gobimportclient/converter.py
src/requirements.txt

This fixes the missing reference fields and bumps the core to 0.2.10

Use fields instead of attributes

---

src/gobimportclient/__main__.py
src/gobimportclient/import_client.py
src/gobimportclient/validator/__init__.py
src/requirements.txt

Basic import validation

---

src/example/metingen.json
src/gobimportclient/__main__.py
src/gobimportclient/enricher/__init__.py
src/gobimportclient/import_client.py
src/gobimportclient/validator/__init__.py
src/requirements.txt

Enrichment for metingen has been added. Data has been verified with the current city data platform. The query has been altered to return the metingen ordered by date, to simplify calculations needed in the enrichment step.

Add basic enrichment

---

src/example/referentiepunten.json
src/requirements.txt

GOBCore has been updated to v0.3.2 and referentiepunten import has been added

Add referentiepunten to import

---

src/example/rollagen.json
src/gobimportclient/import_client.py
src/gobimportclient/reader/objectstore.py
src/gobimportclient/validator/__init__.py
src/tests/test_validator.py

Pirmary key validation is now being executed on the source_id. Rollagen only imports .jpg and validation is fixed to match possible input values.

Fix quality control

---

src/example/meetbouten.json
src/example/meetbouten_small.json
src/example/metingen.json
src/example/metingen_small.json
src/example/referentiepunten.json
src/requirements.txt

Imports were updated to match the correct specifications

Update gobcore to v.0.4.7

---

README.md
src/gobimport/__main__.py
src/gobimport/start/__main__.py
src/requirements.txt

A special start-import message is published on the message broker.
Attached is a dataset, read from a file (eg meetbouten.json)
The import client subscribes to start-import messages.
When a start-import message is received the dataset is imported

Start imports via message broker

---

src/gobimport/import_client.py

Remove link to obsoloete ImportMessage class

Include catalogue in import message

---

src/gobimport/connector/database.py
src/gobimport/connector/file.py
src/gobimport/connector/objectstore.py
src/gobimport/import_client.py

Database: username@database
Objectstore: user@tenant
File: ""

Include user in import logging

---

src/data/metingen.json
src/gobimport/validator/__init__.py
src/requirements.txt

Add extra quality control check for peilmerken

Add publiceerbaar to metingen

---

src/data/test/run_test.sh
src/gobimport/converter.py
src/requirements.txt

Use gobimport to prepare the test
Use gobworkflow to start the test
Use gobapi to evaluatie the test

Re-enable end-2-end tests

---

src/data/peilmerken.json

Small change for the publiceerbaar field

Update peilmerken query

---

src/gobimport/validator/__init__.py

Small fix for quality insurance

Add QA check for publiceerbaar on referentiepunten

---

src/gobimport/import_client.py

If no application is defined, default to source name

Set job identification to the application

---

src/data/meetbouten.json
src/gobimport/validator/__init__.py
src/requirements.txt
src/test.sh
src/tests/fixtures.py
src/tests/test_validator.py

Publiceerbaar set to 1 (True) or 0 (False)
instead of Y (True) or N (False)
Validation logic is adjusted to check for valid values

Publiceerbaar YN => 10

---

src/data/bouwblokken.json
src/data/buurten.json

Bouwblokken (BBK) 	0363 0 99 0000000
Buurten (BRT) 	    0363 0 98 0000000

Bouwblokken en buurten identification

---

src/gobimport/connector/database.py

Oracle was returning ASCII instead of UTF-8

Set NLS_LANG to UTF-8

---

src/data/ggpgebieden.json
src/data/ggwgebieden.json
src/gobimport/enricher/__init__.py
src/gobimport/enricher/gebieden.py
src/gobimport/import_client.py
src/gobimport/reader/objectstore.py
src/gobimport/validator/__init__.py
src/requirements.txt
src/test.sh
src/tests/enricher/test_enrich_gebieden.py
src/tests/test_reader.py

GGW = GebiedsGericht Werken gebieden
GGP = GebiedsGericht werken Praktijkgebieden
Both import are Excel files stored in Objectstore.
Enrichment is used to add missing data (eg identificatie)
and to interpret data in the correct format.

Add GGW, GGP imports

---

src/data/ggpgebieden.json
src/data/ggwgebieden.json

Generate geometry by adding geometries from other entities

---

src/data/test/test.json
src/data/test/test_ADD.csv
src/data/test/test_DELETE.csv
src/data/test/test_DELETE_ALL.csv
src/data/test/test_MISSING.csv
src/data/test/test_MODIFY.csv
src/data/test/test_NON_BOOLEAN.csv
src/data/test/test_NON_CHARACTER.csv
src/data/test/test_NON_DATE.csv
src/data/test/test_NON_DECIMAL.csv
src/data/test/test_NON_GEOMETRY.csv
src/data/test/test_NON_INTEGER.csv
src/data/test/test_NON_JSON.csv
src/gobimport/validator/__init__.py
src/requirements.txt

Fixes https://datapunt.atlassian.net/browse/GOB-519
Sub-task of https://datapunt.atlassian.net/browse/GOB-511
JSON Type was missing from the e2e.

Added JSON to e2e test types

---

src/data/bouwblokken.diva.json
src/data/bouwblokken.json
src/data/buurten.diva.json
src/data/buurten.json
src/data/ggpgebieden.json
src/data/ggwgebieden.json
src/data/meetbouten.json
src/data/metingen.json
src/data/peilmerken.json
src/data/referentiepunten.json
src/data/stadsdelen.diva.json
src/data/stadsdelen.json
src/data/wijken.diva.json
src/data/wijken.json
src/data/woonplaatsen.json
src/gobimport/converter.py
src/gobimport/enricher/gebieden.py
src/requirements.txt
src/tests/enricher/test_enrich_gebieden.py

Imports were changed to match latest model and specs

Large rename of model and attributes

---

src/gobimport/enricher/gebieden.py

Provide each warning with an id
So that the warnings can be reported as a group
In the management Frontend

Tag warnings

---

src/requirements.txt

Latest gobcore

---

src/data/test/test.json
src/data/test/test_ADD.csv
src/data/test/test_DELETE.csv
src/data/test/test_DELETE_ALL.csv
src/data/test/test_EMPTY.csv
src/data/test/test_MISSING.csv
src/data/test/test_MODIFY.csv
src/data/test/test_NON_BOOLEAN.csv
src/data/test/test_NON_CHARACTER.csv
src/data/test/test_NON_DATE.csv
src/data/test/test_NON_DATETIME.csv
src/data/test/test_NON_DECIMAL.csv
src/data/test/test_NON_GEOMETRY.csv
src/data/test/test_NON_INTEGER.csv
src/data/test/test_NON_JSON.csv
src/data/test/test_NON_POINT.csv
src/data/test/test_NON_POLYGON.csv
src/data/test/test_NON_REFERENCE.csv

FIXES #GOB-522 https://datapunt.atlassian.net/browse/GOB-522
Reference type is added to all e2e tests.
And added negative test for reference.

Added reference type to e2e tests

---

src/gobimport/enricher/__init__.py
src/gobimport/entity_validator/__init__.py
src/gobimport/entity_validator/gebieden.py
src/gobimport/import_client.py
src/gobimport/validator/__init__.py
src/test.sh
src/tests/entity_validator/test_enrich_gebieden.py
src/tests/entity_validator/test_entity_validator.py

Validations for gebieden were added. An entity validation step was added to be able to check certain values after being converted to GOBTypes. This was mainly needed to be able to compare dates without any knowledge about the format. Geometry tests were enhanced to also check each point in a polygon

Add QA checks for gebieden

---

src/gobimport/__main__.py
src/gobimport/import_client.py

The contents of the message header that is received
Is copied into the header of the result message

Replicate message header

---

src/gobimport/enricher/__init__.py
src/gobimport/enricher/gebieden.py
src/gobimport/enricher/meetbouten.py
src/gobimport/entity_validator/__init__.py
src/gobimport/entity_validator/gebieden.py
src/gobimport/import_client.py
src/gobimport/validator/__init__.py
src/requirements.txt
src/tests/enricher/test_enrich.py
src/tests/enricher/test_enrich_gebieden.py
src/tests/enricher/test_enrich_meetbouten.py
src/tests/entity_validator/test_enrich_gebieden.py
src/tests/entity_validator/test_entity_validator.py
src/tests/test_validator.py

Use shared logger logic from GOB-Core

Use GOB-Core logger

---

src/.flake8
src/gobimport/converter.py
src/gobimport/entity_validator/__init__.py
src/requirements.txt
src/tests/entity_validator/test_entity_validator.py

The state logic is encapsulated by GOB-Core
Entities are checked for multiple instances without enddate (warning)

Use model has_states logic

---

src/data/bouwblokken.json
src/data/buurten.json
src/data/stadsdelen.json
src/data/wijken.json
src/requirements.txt

Instead of adding new volgnummers
Overwrite the last volgnummer of DIVA

Overwrite DIVA volgnummer by DGDialog

---

src/data/bouwblokken.diva.json
src/data/bouwblokken.json
src/data/buurten.diva.json
src/data/buurten.json
src/data/ligplaatsen.json
src/data/meetbouten.json
src/data/metingen.json
src/data/nummeraanduidingen.json
src/data/openbareruimtes.json
src/data/panden.json
src/data/peilmerken.json
src/data/referentiepunten.json
src/data/stadsdelen.diva.json
src/data/stadsdelen.json
src/data/standplaatsen.json
src/data/verblijfsobjecten.json
src/data/wijken.diva.json
src/data/wijken.json
src/data/woonplaatsen.json
src/gobimport/connector/__init__.py
src/gobimport/connector/oracle.py
src/gobimport/entity_validator/gebieden.py
src/gobimport/import_client.py
src/gobimport/reader/__init__.py
src/gobimport/reader/oracle.py
src/tests/enricher/test_enrich_bag.py
src/tests/test_import_client.py

Using cx_oracle library directly results in a major performance upgrade. All imports have been changed to use this reader instead of the regular SQLAlchemy library.

Oracle connector

---

src/gobimport/enricher/meetbouten.py
src/requirements.txt

Small fix for meetbouten enrichment

Update gobcore to offload large messages

---

src/data/meetbouten.json
src/data/referentiepunten.json
src/gobimport/converter.py
src/test.sh

Literal values start with "=", eg "=geometrie"

Add literal source values to the import spec

---

src/data/meetbouten.json
src/data/referentiepunten.json
src/gobimport/converter.py
src/test.sh

Literal values start with "=", eg "=geometrie"

Release 20190320

---

src/data/ligplaatsen.json
src/data/panden.json
src/data/standplaatsen.json
src/data/verblijfsobjecten.json

For relations we make on geometry a value of ‘geometrie’ is added to bronwaarde to show how the connection is made

Add geometrie as bronwaarde

---

src/requirements.txt

Set prefetch count to 1 to solve duplication of messages

Update GOB Core version, Prefetch count 1

---

src/data/test/test.json

Change the E2E test to match the current way of adding references

Fix e2e tests

---

src/data/bouwblokken.diva.json
src/data/bouwblokken.json
src/requirements.txt

Use geometry to determine relationships between bouwblokken and buurten

Update bouwblokken imports

---

src/data/rollagen.json

Match current objectstore layout

Fix rollagen import

---

src/data/bouwblokken.diva.csv.json
src/data/bouwblokken.diva.json
src/data/bouwblokken.json
src/data/buurten.diva.csv.json
src/data/buurten.diva.json
src/data/buurten.json
src/data/ligplaatsen.json
src/data/meetbouten.json
src/data/metingen.json
src/data/nummeraanduidingen.json
src/data/openbareruimtes.json
src/data/panden.json
src/data/peilmerken.json
src/data/referentiepunten.json
src/data/stadsdelen.diva.csv.json
src/data/stadsdelen.diva.json
src/data/stadsdelen.json
src/data/standplaatsen.json
src/data/verblijfsobjecten.json
src/data/wijken.diva.csv.json
src/data/wijken.diva.json
src/data/wijken.json
src/data/woonplaatsen.json

Added expiration date to queries and mapping for entities where expiration date has been defined

Add expiration date to queries and mapping

---

src/data/test/test.json
src/gobimport/import_client.py

E2E DeleteAll failed because imported set was empty
However, for the test catalog this is valid
Fix data import path for test collection

Allow for empty test sets

---

src/data/ggpgebieden.json
src/data/ggwgebieden.json

The geometry is derived from the geometry of the buurten

GGW and GGP gebieden depend on buurten

---

src/data/nummeraanduidingen.json

GOB-1045
If ligt_in_woonplaats contains 1024;3594 or 1025;3594 we select the correct woonplaats based on the opvoerdatum. Before 2014-01-10 is 1024/1025, after that it’s 3594

Update NAG import

---

src/data/bgt.onderbouw.json

Trim curly braces from identificatie

Update onderbouw import

---

src/data/brk.kadastraleobjecten.json

Update kadastraleobjecten import to get the correct bronwaarde for relations to kadastralegemeentes, kadastralegemeentecodes and kadastralesecties

Update KOT import

---

src/data/verblijfsobjecten.json
src/gobimport/import_client.py

Only issue error messages for empty datasets if mode is FULL_IMPORT
Partial imports are very well allowed to return empty datasets

Recent BAG verblijfsobjecten set to 10 days

---

src/data/openbareruimtes.json
src/data/verblijfsobjecten.json
src/data/woonplaatsen.json
src/gobimport/enricher/bag.py
src/requirements.txt
src/tests/enricher/test_enrich_bag.py

Get straatcode from Neuron instead of the DIVA file and add extra attributes needed for UVA2

Add import of uva2 attributes

---

src/data/verblijfsobjecten.json

Rownum limitation was there for testing purposes...

Remove rownum from import query

---

src/data/brk.aantekeningenkadastraleobjecten.json
src/data/brk.aantekeningenrechten.json
src/data/brk.aardzakelijkerechten.json
src/data/brk.kadastralegemeentecodes.json
src/data/brk.kadastralegemeentes.json
src/data/brk.kadastraleobjecten.json
src/data/brk.kadastralesecties.json
src/data/brk.kadastralesubjecten.json
src/data/brk.meta.json
src/data/brk.stukdelen.json
src/data/brk.tenaamstellingen.json
src/data/brk.zakelijkerechten.json

Merge to master with https://github.com/Amsterdam/GOB-Prepare/pull/166

GOB-1256 Import from new BRK schema name

---

src/data/secure.csv.json
src/gobimport/converter.py
src/gobimport/reader.py
src/requirements.txt
src/tests/test_reader.py

Import references with secure attributes

Secure Reference in Import

---

src/data/ligplaatsen.json
src/data/nummeraanduidingen.json
src/data/openbareruimtes.json
src/data/panden.json
src/data/standplaatsen.json
src/data/verblijfsobjecten.json
src/data/woonplaatsen.json

Don't merge before GOB-Upload!

PGB-1027 Generate Amsterdamse Sleutel

---

src/data/ggpgebieden.json
src/data/ggwgebieden.json

so _expiration_date will be set when enddate for that record is set.

Fixed imports of ggwgebieden and ggpgebieden 

---

src/requirements.txt

Fixes issue with QA-Catalog updates

Update GOB-Core version

---

src/requirements.txt

Begin- and eind-geldigheid have been added

Update GOB-Core for QA catalog update

---

src/requirements.txt

Automated update of GOB-Core to its latest version

Update GOB-Core version from v0.15.6a to v0.15.7

---

src/gobimport/converter.py
src/requirements.txt
src/tests/test_converter.py

Parse format specification of GOB ManyReference string value

PGB 1319 aanduiding in onderzoek

---

src/requirements.txt

To use BAG Import queries without BAG onderzoeken relation

Update GOB-Config to v0.4.7

---

src/requirements.txt

Updated Core and Config version

PGB-1576 Config to 0.4.11b and Core to 0.16.7l

---

src/requirements.txt

Automated update of shared lib(s) to their latest version

Update GOB-Config v0.4.11f to v0.4.11g

---

src/gobimport/enricher/bag.py
src/requirements.txt
src/tests/enricher/test_enrich_bag.py
src/tests/entity_validator/test_state_validator.py

JSON arrays are imported for verblijfsobjecten so the enrich steps can be removed

Import JSON arrays for verblijfsobjecten

---

src/gobimport/validator/__init__.py
src/requirements.txt

Check on valid geometrie must be adjusted, currently raises an error on import BAG OpenbareRuimtes

Fix issue with import BAG OpenbareRuimtes

---

src/gobimport/validator/__init__.py
src/requirements.txt

Requires Core update https://github.com/Amsterdam/GOB-Core/pull/621

Add BAG Neuron identificatie check if value startswith 0363

---

src/Dockerfile
src/requirements.txt

Also update Oracle drivers to 21.4 and remove some unused dependencies

Update config and core

---

src/gobimport/config.py
src/gobimport/enricher/enricher.py
src/gobimport/enricher/gebieden.py
src/requirements.txt
src/test.sh
src/tests/enricher/test_enrich.py
src/tests/enricher/test_enrich_bag.py
src/tests/enricher/test_enrich_gebieden.py
src/tests/enricher/test_enrich_meetbouten.py
src/tests/enricher/test_enrich_test_catalogue.py
src/tests/entity_validator/test_gebieden_validator.py
src/tests/entity_validator/test_init.py

Remove CBS api enricher, add static cbs code table

---

src/gobimport/enricher/gebieden.py
src/gobimport/entity_validator/gebieden.py
src/gobimport/validator/__init__.py
src/requirements.txt
src/tests/enricher/test_enrich_gebieden.py
src/tests/entity_validator/test_gebieden_validator.py

Adapt to model changes in gebieden

---

src/gobimport/__main__.py
src/gobimport/import_client.py
src/requirements.txt
src/tests/test_main.py

- if args are given, start standalone
- no args, connect to messagebroker
- requires https://github.com/Amsterdam/GOB-Core/pull/649

Import as standalone application

---

src/gobimport/__main__.py
src/requirements.txt
src/tests/test_main.py

Write path to results in xcom message

---

docker-compose.yml

This is required to make it run in airflow-local

Name gobimport image gob_import like in jenkins

---

src/requirements.txt

Placeholder PR -> Need to update Core and Config

Update Core and Config for gebieden from AMS Schema

---

src/Dockerfile
src/gobimport/__main__.py
src/gobimport/import_client.py
src/requirements.txt
src/tests/test_main.py

[AB#49818](https://dev.azure.com/CloudCompetenceCenter/7755cdf4-1859-48c5-b954-fd6c8e46fe52/_workitems/edit/49818)

49818-standalone import

---

src/Dockerfile
src/gobimport/__main__.py
src/gobimport/import_client.py
src/requirements.txt
src/tests/test_main.py

* Make standalone run generic with other services
* Move logger configuration out of handler
* Update gobcore version
* Tweaked argparse required arguments and descriptions
Co-authored-by: Roel de Vries <77724088+roel-devries@users.noreply.github.com>

49818-standalone import (#749)

---

Jenkinsfile
README.md
docker-compose.yml
src/.jenkins/test/docker-compose.yml
src/Dockerfile
src/gobimport/__main__.py
src/gobimport/import_client.py
src/pytest.ini
src/requirements.txt
src/test.sh
src/tests/test_main.py

49818-standalone import (#749)
* Make standalone run generic with other services
* Move logger configuration out of handler
* Update gobcore version
* Tweaked argparse required arguments and descriptions
Co-authored-by: Roel de Vries <77724088+roel-devries@users.noreply.github.com>

Run as user datapunt.

---

src/requirements.txt

Need to set Core version after https://github.com/Amsterdam/GOB-Core/pull/675 is merged
Need to set Config version after https://github.com/Amsterdam/GOB-Config/pull/125 is merged

Update Core and Config with Amsterdam Schema MBN update

---

src/requirements.txt

* Update Core and Config with Amsterdam Schema MBN update
* Update requirements.txt

Update Core and Config with Amsterdam Schema MBN update (#753)

---

src/gobimport/__main__.py
src/requirements.txt

Remove logging.configure call + update core

Remove logging configure (#754)

---

src/.flake8
src/gobimport/__init__.py
src/gobimport/converter.py
src/gobimport/entity_validator/__init__.py
src/gobimport/entity_validator/state.py
src/gobimport/reader.py
src/gobimport/validator/__init__.py
src/requirements.txt
src/test.sh
src/tests/entity_validator/test_init.py
src/tests/entity_validator/test_state_validator.py
src/tests/test_converter.py
src/tests/test_import_client.py
src/tests/test_reader.py
src/tests/test_validator.py

* Refactored GOB-Import to use GOBModel dictionary methods.
* Fixed tests.
* EntityValidator.validate test.

Refactored GOB-Import to use GOBModel dictionary methods. (#761)

---

src/gobimport/converter.py
src/requirements.txt

* Log fix for _extract_field error.
* Update GOB Core and Config -- BRK2 KOT.

BRK2 kadastraleobjecten (#770)

---

src/gobimport/__main__.py
src/requirements.txt

Needs update of GOB-Core once https://github.com/Amsterdam/GOB-Core/pull/687 is merged

Update gobcore. Use pass_args_standalone to explicitly accept the 'mode' parameter

---

src/.flake8
src/Dockerfile
src/gobimport/__init__.py
src/pyproject.toml
src/pytest.ini
src/requirements.txt
src/test.sh

* Add standard code checks to repo
- mypy
- pytest
- coverage
- black
- isort
- flake8
* Move flake8 to pyproject.toml
* Allow per file enable checks
* Uncomment/enable __init__.py
* Replace .flake8 and pytest.ini in test dockerfile
* Linelength = 120
* Update GOB-core to v2.3.0
* Omit gobcore/config in coverage run
* Add folder to coverage, remove omits

Add standard code checks to repo (#792)

---

src/pyproject.toml
src/test.sh

Move some black cli arguments to pyproject.toml

---

src/gobimport/__main__.py
src/gobimport/enricher/__init__.py
src/gobimport/enricher/bag.py
src/gobimport/enricher/enricher.py
src/gobimport/enricher/gebieden.py
src/gobimport/enricher/meetbouten.py
src/gobimport/enricher/test_catalogue.py
src/gobimport/entity_validator/__init__.py
src/gobimport/entity_validator/bag.py
src/gobimport/entity_validator/gebieden.py
src/gobimport/entity_validator/state.py
src/gobimport/import_client.py
src/gobimport/injections.py
src/gobimport/merger.py
src/gobimport/reader.py
src/pyproject.toml
src/requirements.txt
src/test.sh
src/tests/test_merger.py

Code checks for gobimport. (#805)

---

src/requirements.txt

Update GOB-Config to v0.13.2

---

src/gobimport/entity_validator/bag.py
src/requirements.txt

Need to update GOB-Core to release version later

Update import to be able to handle imports from adb-prepared data
